name: app-build

on:
  push:
    branches:
      - main

jobs:
  build-and-push-2-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Container Registry
        run: echo $DOCKER_HUB_TOKEN | docker login -u lemonpro --password-stdin
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and containerize application
        run: |
          docker build -t zlack:1.0.0-SNAPSHOT .
      - name: Tag & push to DockerHub Registry
        run: |
          docker tag zlack:1.0.0-SNAPSHOT index.docker.io/lemonpro/zlack:latest
          docker push index.docker.io/lemonpro/zlack:latest
